### ISSUE TITLE
No paskal/bitrix-php

### ISSUE THREAD

**Issue by AndreyChursin** [paskal/bitrix.infra#2]
DMITRY VERKHOTUROV removed image paskal/bitrix-php and what now?

**Comment by paskal** [comment]
Thanks for the report! `docker-compose up --build -d` supposed to build that image before using it, but you're the second person telling me they didn't use `--build` flag, so I pushed the image [to the DockerHub](https://hub.docker.com/repository/docker/paskal/bitrix-php), now it will work without a build. Resolving, feel free to reopen.
