### ISSUE TITLE
Why you run php-cron in separated container?

### ISSUE THREAD

**Issue by AndreyChursin** [paskal/bitrix.infra#3]
Why you run php-cron in separated container but not in same php container?

**Comment by paskal** [comment]
Good question! The docker container is supposed to have one task and one task only, which translates to running a single binary in real life. To use PHP for serving web requests, we need to run a php-fpm daemon (`/usr/sbin/php-fpm7.4 -O`, [link](https://github.com/phpdocker-io/base-images/blob/93dd141/php/7.4/fpm/Dockerfile#L18)) and expose it to the Nginx via the port. To use cron, we need to run cron daemon (`cron -f`, [link](https://github.com/paskal/bitrix.infra/blob/7517128/docker-compose.yml#L97)).

That separation provides us with separate logs per container, which is useful when one is serving web requests, and another is running the scheduled tasks; however, it's not used here as a cron container (supposed) not to write anything to stdout.

There are multiple other benefits of the separation of these two functions into two separate containers, but I can't think of any single one which would be applicable in this case, and I do see the downside of having a duplicate configuration for the php-cron container as it needs to access the same volumes and containers to work.

Having both cron and PHP workers running in the same container would be more confusing to someone who used to run a single function per container; however, it will remove one extra place of complexity. I'll see if I can make it work to preserve the clarity of the setup.

**Comment by paskal** [comment]
I thought about it for some more time and understood that I want to leave it the current way instead of running multiple processes in a single container. Docker doesn't encourage coupling multiple processes into a single container and I don't want to go against the usual pattern that the system encourages.
